'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.235
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TicketYa.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1350171020_tick_circle() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350171020_tick_circle", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350171138_cancel() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350171138_cancel", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350171151_Profile() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350171151_Profile", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350171195_edit_language() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350171195_edit_language", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350171251_license() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350171251_license", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350171308_book() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350171308_book", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350171334_application_exit() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350171334_application_exit", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350171451_backup_restore() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350171451_backup_restore", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350171472_people() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350171472_people", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350171726_ticket() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350171726_ticket", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350172131_data_management() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350172131_data_management", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350172161_configuration() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350172161_configuration", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350172417_lock_unlock() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350172417_lock_unlock", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350172460_system_config_language() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350172460_system_config_language", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350172478_Language() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350172478_Language", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350172894_xmag() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350172894_xmag", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350172977_folder_new() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350172977_folder_new", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property _1350173099_Modify() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1350173099_Modify", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property whiteCrossBlueBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("whiteCrossBlueBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
